export default {
  'CET-4': {
    Day1: [
      'conservation',
      'enrol',
      'summit',
      'specialize in',
      'resident',
      'radical',
      'rag',
      'prescribe',
      'manner',
      'beneath',
      'recreation',
      'procession',
      'tackle',
      'resort n/v',
      'resort to',
      'broom',
      'recruit',
      'superb',
      'bloody',
      'fierce',
      'enquire',
      'emit',
      'superficial',
      'drip',
      'sole',
      'folk',
      'enclose',
      'gamble',
      'loophole',
      'ornament',
      'paradox',
      'awe',
      'bail',
      'bold',
      'socalled',
      'superior',
      'damn',
      'erroneous',
      'fatal',
      'excursion',
      'ignorant',
      'county',
      'condense',
      'asset',
      'rear',
      'bring up the rear',
      'hollow',
      'charter',
      'astonish',
      'cabbage',
      'condemn',
      'surplus',
      'eliminate',
      'eliminate the possibility',
      'alike',
      'phenomenon',
      'curtain',
      'bystander',
      'bait',
      'extinguish',
      'federation',
      'grin',
      'hatch',
      'hatch out',
      'irrational',
      'layoff',
      'norm',
      'decisive',
      'play a decisive role in',
    ],
  },
  TOEFL: {},
};
