export default {
  'CET-4': {
    Day1: [
      'lad',
      'frown',
      'stir',
      'supreme',
      'limb',
      'sector',
      'clash',
      'grant',
      'appliance',
      'derive from',
      'derive sth from sth',
      'proportion',
      'scandal',
      'abolish',
      'fable',
      'paddy',
      'aerial',
      'domestic',
      'rebel',
      'stem',
      'stem from',
      'render',
      'stiff',
      'rug',
      'stimulate',
      'rouse',
      'barrier',
      'delegate',
      'latter',
      'stoop',
      'deem',
      'ferry',
      'jetlag',
      'submerge',
      'stove',
      'strain',
      'strap',
      'exclaim',
      'discipline',
      'mayor',
      'ripe',
      'likewise',
      'overnight',
      'bearing',
      'striking',
      'abuse',
      'strip',
      'crude',
      'hedge',
      'indispensable',
      'scheme',
      'accustom',
      'accustom sb to sth',
      'impulse',
      'fireplace',
      'gown',
      'haul',
      'criterion',
      'beforehand',
    ],
    Day2: [
      'congress',
      'bump',
      'bump aginst/into',
      'stroke',
      'pinch',
      'a pinch of sth',
      'exploit',
      'bulk',
      'grave n/adj',
      'brow',
      'penetrate',
      'distraction',
      'pole',
      'be poles apart',
      'drain',
      'charity',
      'span',
      'spite',
      'out of spite (because of spite)',
      'slender',
      'substance',
      'contest',
      'insane',
      'lame',
      'kin',
      'watertight',
      'veto',
      'civilize',
      'purse',
      'courtyard',
      'rural',
      'fortnight',
      'disgust',
      'sheer',
      'cupboard',
      'sore',
      'raid',
      'distress',
      'rack n/v',
      'deny',
      'genuine',
      'suburb',
      'dean',
      'badge',
      'irrigate',
      'lass',
      'gut n/adj',
      'habitat',
      'reap',
      'paperback',
      'scent',
      'briefcase',
      'defect',
      'attribute',
      'attribute sth to sth',
      'privilege',
      'dull',
      'provoke',
      'substitute',
      'allowance',
      'suck',
      'court',
      'curl v/n',
      'moist',
      'restless',
      'dip',
      'lease n/v',
      'disposal',
      'appeal',
      'appeal against ...',
      'reckon',
      'reckon on sth',
      'jury',
      'reception',
      'merit',
      'compromise',
      'rally n/v',
      'vendor',
      'surge',
      'tablet',
      'recite',
      'odour',
      'hyphen',
      'corporate',
    ],
    Day3: [
      'conservation',
      'enrol',
      'summit',
      'specialize in',
      'resident',
      'radical',
      'rag',
      'prescribe',
      'manner',
      'beneath',
      'recreation',
      'procession',
      'tackle',
      'resort n/v',
      'resort to',
      'broom',
      'recruit',
      'superb',
      'bloody',
      'fierce',
      'enquire',
      'emit',
      'superficial',
      'drip',
      'sole',
      'folk',
      'enclose',
      'gamble',
      'loophole',
      'ornament',
      'paradox',
      'awe',
      'bail',
      'bold',
      'socalled',
      'superior',
      'damn',
      'erroneous',
      'fatal',
      'excursion',
      'ignorant',
      'county',
      'condense',
      'asset',
      'rear',
      'bring up the rear',
      'hollow',
      'charter',
      'astonish',
      'cabbage',
      'condemn',
      'surplus',
      'eliminate',
      'eliminate the possibility',
      'alike',
      'phenomenon',
      'curtain',
      'bystander',
      'bait',
      'extinguish',
      'federation',
      'grin',
      'hatch',
      'hatch out',
      'irrational',
      'layoff',
      'norm',
      'decisive',
      'play a decisive role in',
    ],
    Day4: [
      'invest',
      'invest in sth',
      'synthetic',
      'curse n/v',
      'suspect n/v',
      'suspend',
      'tide',
      'the tide is in/out',
      'cope with',
      'barely',
      'joint adj',
      'joint effort',
      'surrender',
      'faint',
      'faint noise/light',
      'swallow',
      'hazard',
      'sth is hazzard to sth',
      'miracle',
      'sway',
      'swell/swollen',
      'swift',
      'swift to do sth',
      'fibre',
      'Foot and vegetables are hight in fibers.',
      'pension',
      'sanction',
      'US sanctions against Cuba',
      'liable to',
      'breeze',
      'customs',
      'customs duties',
      'deficit',
      'expressway',
      'ballot',
      'overhear',
      'patent',
      'hospitable',
      'relay',
      'a relay race',
      'dock',
      'considerable',
      'considerable amount/number of sth',
      'spur',
      'on the spur of the moment',
      'We would often decide what to play on the spur of the moment.',
      'infant',
      'symptom of',
      'pillar',
      'conscience',
      'aginst my conscience',
      'cable',
      'screw/nail',
      'screw sth into/onto/to sth',
      'screw up',
      'gang',
      'constitute',
      'seal',
      'saint',
      'immense',
      'ridge',
      'competent',
      'competent to do sth',
      'pulse / pause',
      'encounter problems/defficulties',
      'pond',
      'flee',
      'fluctuate',
      'flunctuate between A and B / flunctuate around ...',
      'curb',
      'curb the spread of the virus',
      'defy',
      'authorize sb to do sth',
      'foresight',
      'bandage',
      'expertise',
      'haunt',
      'marsh',
      'nourish',
      'orphan',
    ],
    Day5: [
      'consistent',
      'technician',
      'tedious',
      'famine',
      'plural',
      'discharge',
      'extensive',
      'temper',
      'decay',
      'in accordance with sth',
      'in accordance with the law',
      'perceive',
      'scarcely',
      'scarcely ... when ...',
      'He had scarcely sat down when there was a knock at the door.',
      'conductor',
      'frank',
      'be frank with sb',
      'be frank about sth',
      'hip',
      'temptation',
      'tempt',
      'disguise',
      'solemn',
      'strive for / strive to be ...',
      'tangible',
      'undermine',
      'dent',
      'exile',
      'irony/ironic',
      'consent',
      'miserable',
      'antique',
      'liquor',
      'presently',
      'nerve',
      'cement',
      'magnificent',
      'tender',
      'tense',
      'then tense silence',
      'oversee',
      'auditorium',
      'banquet',
      'excel',
      'excel in/at',
      'deprive',
      'overdue',
      'formulate',
      'formulate a policy/plan/strategy',
      'incentive',
      'attic',
      'nap',
      'take a nap',
      'flaw',
      'flawless',
      'a flaw in sth',
    ],
    Day6: [
      'propse',
      'propse to do sth',
      'terminal',
      'terminal cancer',
      'pursue',
      'pursue a goal/aim/carrier...',
      'territory',
      'tone',
      'incline',
      'incline to do sth',
      'incline to the opinion',
      'liberal',
      'constitution',
      'amateur',
      'textile',
      'textile industry',
      'notion',
      'hatred',
      'durable',
      'barrel',
      'criminal',
      'accuse',
      'accuse sb of doing sth',
      'reveal',
      'induce',
      'basement',
      'forthcoming',
      'hinder',
      'ethnic',
      'nasty',
      'deteriorate',
      "sb's health has deteriorate",
      'bachelor',
      "bachlor's degree",
      'aptitude for',
      'entrepreneur',
      'clue',
      'conjunction',
      'in conjunction with',
      'The worksheets are designed to be used in conjunction with the new coursebooks.',
      'lord',
      'cease',
      'obligation',
      'consult',
      'insurance',
      'merchant',
      'fertile',
      'retreat',
      'thoughtful',
      'chamber',
      'ratio',
      'ratio of A to B',
      'estate',
      'belly',
      'lide down on your belly',
      'dew',
      'ample',
      'apparatus',
      'betray',
      'counterpart',
    ],
    Day7: [
      'petroleum',
      'petrol',
      'horsepower',
      'suspicion',
      'under suspicion',
      'prospect',
      'conduct n/v',
      'lawn',
      'transmit',
      'slip',
      'thrive',
      'recession',
      'prominent',
      'spark',
      'mug n/v',
      'elastic n/adj',
      'presumably',
      'chief',
      'thrust',
      'monument',
      'ease',
      'with ease',
      'assess',
      'drift',
      'dismiss',
      'deputy',
      'contract',
      'exert oneself',
      'dispose',
      'rage',
      'in a rage',
      'roast',
      'timber',
      'reluctant',
      'alley',
      'dignity',
      'with dignity',
      'lose dignity',
      'cellar',
      'fossil',
      'garment',
      'allege',
      'it is alleged that ...',
      'accountable to',
      'upright',
      'walk upright',
      'furnish',
      'furnish sth with sth',
      'institution',
      'delicate',
      'convey',
      'dairy',
      'consultant',
      'centigrade',
      'precaution',
      'just in case',
      'agenda',
      'conventional',
      'auxiliary',
      'conservative',
      'legistation',
      'gulf',
      'combat',
      'exhibit',
      'fragment',
      'elementary',
      'towel',
      'Celsius',
      'Fahrenheit',
      'bypass',
      'costume',
      'diagnose',
      'diagnosed with sth',
      'mortgage',
      'overthrow',
      'renovate',
      'bully',
      'addict',
    ],
    Day8: [
      'compass',
      'lean 2',
      'lean on',
      'tragedy',
      'comedy',
      'offend',
      'tractor',
      'instinct',
      'trail n/v',
      'prosperity',
      'prosperous',
      'pants',
      'jealous of',
      'dominate',
      'dominant',
      'inspect',
      'lorry',
      'cue',
      'sth is the cue for sth',
      'farewell',
      'revenue',
      'hay',
      'advocate for',
      'specify',
      'pour',
      'assemble',
      'slope',
      'lick',
      'crucial',
      'priest',
      'transparent',
      'fancy adj/v',
      'fancy doing sth',
      'take a fancy to',
      'conscious',
      'biography',
      'cereal',
      'bumper',
      'proficient in/at',
      'repay',
      'bulletin',
      'dilemma',
      'in a dilemma',
      'cosmos',
      'integrity',
      'chill',
      'chilly',
      'flood n/v',
      'species',
      'contemporary music/art',
      'copper',
      'carriage',
      'mat',
      'cashier',
      'sensible',
      'faithful',
      'remedy',
      'remedy my mistake',
      'decent',
      'confine',
      'fruitful',
      'tray',
      'retain',
      'comb',
      'appoint',
      'treaty',
      'the peace treaty',
      'tremble',
      'tremble with rage',
      'navy',
      'tremendous',
      'elaborate',
      'jail',
      'corrupt',
      'diligent',
      'be diligent in doing sth',
      'bud',
      'overwhelm v',
      'overwhelming',
      'chore',
      'buckle',
      'opponent',
    ],
    Day9: [
      'saddle',
      'lest',
      'She turned away from the window lest anyone see them.',
      'trial',
      'inn',
      'choke on',
      'council',
      'lodge v/n',
      'troop',
      'tropical',
      'coil',
      'The snake coiled around the branches of the tree.',
      'peculiar',
      'portrait',
      'utter adj/v',
      'pledge',
      'harsh',
      'trumpet',
      'nonsense',
      'exaggerate',
      'I’m not exaggerating.',
      'trunk 2',
      'grocery',
      'attain',
      'devise',
      'device',
      'tune',
      'handy',
      'pill',
      'ceremony',
      'reservoir',
      'twist',
      'protest against sth',
      'aisle',
      'Would you like a window seat or an aisle seat.',
      'cherish',
      'acquaintance',
      'counsel',
      'sin',
      'companion',
      'sow',
      'frontier',
      'apart',
      'apart from',
      'nevertheless',
      'tyre',
      'impose',
      'nursery',
      'invade',
      'invader',
      'fraction',
      'cabinet',
      'amid',
      'He sat amid the trees.',
      'deposit',
      'faculty 2',
      'dim',
      'earnest',
      'orchestra',
      'arithmetic',
      'heel',
      'oblige',
      'convict',
      'discard',
      'Discard any old clothes.',
      'deceive',
      'brutal',
      'cholesterol',
      'dine',
      'dine out',
      'affluent',
      'dynasty',
      'hijack',
      'influenza',
      'profound',
    ],
    Day10: [
      'comprise',
      'be comprised of sth and sth...',
      'revolve',
      'mold/moldy 2',
      'discrimination 2',
      'virtue',
      'uncover',
      'confront',
      'undergo',
      'dictate',
      'proceed',
      'nitrogen',
      'fluid',
      'drill 2',
      'undertake',
      'jaw',
      'precious',
      'favour',
      'in favour of sth',
      'rival',
      'collapse',
      'corridor',
      'pit',
      'balcony',
      'diplomatic',
      'diplomat',
      'bathe',
      'conquer',
      'inflation',
      'heir',
      'brochure',
      'deficient',
      'endanger v',
      'circus',
      'thermometer',
      'democracy',
      'obstacle to',
      'nuisance',
      'justify',
      'neglect',
      'formation',
      'punctual',
      'relieve',
      'herd n/v',
      'a herd of cattle',
      'mineral',
      'lane',
      'beloved',
      'exclusive 3',
      'palm',
      'namely',
      'heave',
      'excessive',
      'headquarters',
      'dropout',
      'contaminate',
      'cornerstone',
      'dove',
      'contempt for',
      'diploma',
    ],
    Day11: [
      'uneasy about',
      'torture',
      'incident',
      'myth',
      'trim adj/v',
      'restrain',
      'flock of',
      'coordinate v/n',
      'restore 2',
      'receipt',
      'Keep your receipt in case you want to bring it back.',
      'bloom',
      'specimen',
      'utmost',
      'the utmost importance',
      'to the utmost',
      'vacant',
      'dose',
      'vacuum',
      'vaccum cleaner',
      'barn',
      'initiative 2',
      'compel',
      'bribe',
      'proclaim',
      'stride v/n 2',
      'basis',
      'rib',
      'butcher',
      'triumph',
      'trump',
      'maid',
      'soak',
      'van',
      'vanish 2',
      'sake',
      'for the sake of sth/sb',
      'vapour',
      'haste',
      'coach 2',
      'grace',
      'ditch',
      'pint',
      'scout',
      'fountain',
      'conscientious',
      'acquaint',
      'acquaint sb with sth',
      'hectare',
      'invariably',
      'eternal',
      'eternity',
      'pastime',
    ],
    Day12: [
      'skim',
      'vigorous',
      'vigor',
      'rifle',
      'stake n/v',
      'stake sth on sth',
      'depress',
      'disorder',
      'slam',
      'sleeve',
      'luggage',
      'venture n/v',
      'accustomed',
      'be accustomed to do sth',
      'be used to do sth',
      'memorandum',
      'compulsory',
      'hereby',
      'conform 2',
      'conform to/with',
      'comply',
      'comply with',
      'disintegrate',
      'heritage',
      'doom n/v',
      'doomed to die',
      'shiver with cold/fear',
      'rotten',
      'dash 2',
      'rigid',
      'entertain',
      'vessel 2',
      'a fisshing vessel',
      'a blood vseesl',
      'veteran',
      'regulation',
      'rub',
      'vibrate',
      'vibration',
      'indifferent',
      'plot 3',
      'a plot against the king',
      'The plot was a little confusing.',
      'horror n',
      'fatigue n',
      'vice',
      'chop',
      'infect/infection/infectious',
      'concrete n/adj',
      'erect',
      'vinegar',
      'penalty',
      'compensate',
      'dizzy',
    ],
    Day13: [
      'dump n/v',
      'criticize',
      'criticism',
      'dispute',
      'sigh',
      'reserve',
      'pine n/v',
      'hen',
      'blade',
      'sack 3',
      'a sack of potato',
      'He was sacked from every other job he had.',
      'The Goths sacked Rome.',
      'laundry 2',
      'ambulance',
      'insist',
      'flourish v',
      'property',
      'shave',
      'shaver',
      'enormous',
      'conceal',
      'curriculum',
      'loaf 2',
      'a loaf of bread',
      'They spend all day loafing around on street corners.',
      'stain n/v',
      'invaluable',
      'misfortune',
      'pave',
      'pave the way for sth',
      'clearcut',
      'climax',
      'extent',
      'to an extent',
      'I do agree with him to an extent.',
      'marvelous',
      'respective',
      'boast',
      'sew',
      'utilize',
      'chase',
      'chase after',
      'prevail / prevalence / prevalent',
      'dense',
      'scatter',
      'interfere in',
      'compound',
      'learned',
      'shed',
      'vivid',
      'vivid memories/dreams/descriptions',
      'outset',
      'at/from the outset',
      'mill n/v',
      'ally n/v',
      'brass',
      'brass instrument',
      'engage in',
      'brandy',
      'cling',
      'cling to',
      'riddle',
      'vulnerable',
    ],
    Day14: [
      'standpoint',
      'from a economic/technical/polical standpoint',
      'volt/voltage',
      'canal',
      'the Panama Canal',
      'bet',
      'bet sb that',
      'spade',
      'oval',
      'adequate',
      'cop',
      'sophisticated',
      'damp',
      'permanent',
      'furnace',
      'wagon',
      'waist',
      'plunge',
      'wander around',
      'luxury',
      'in luxury',
      'readily 2',
      'devil',
      'persevere v',
      'clown',
      'seige',
      'sip',
      'trifle 2',
      'a trifle unexpected',
      'brag',
      'resemble v',
      'perception',
      'residence/resident',
      'scold',
      'intense adj',
      'speculate',
      'glove',
      'reputation',
      'spill',
      'regarding',
      'spectacular',
      'fare',
      'convention',
      'By convention',
      'classify',
      'dissolve',
      'splendid',
      'ribbon',
      'scarce',
      'clumsy',
      'ax',
      'frost',
      'compact v/adj',
      'ward',
      'pistol',
      'setback',
    ],
    Day15: [
      'weave',
      'crane',
      'inquire',
      'dialect',
      'weed',
      'lump 2',
      'a lump of butter',
      'shield',
      'diameter',
      'soar',
      'The price of petrol has soared in recent weeks.',
      'molecule / atom',
      'organ 3',
      'grind',
      'freshly ground pepper',
      'riot',
      'porter 2',
      'dusk',
      'somewhat',
      'The price is somewhat higher than I expected.',
      'weep',
      'kneel v',
      'welfare',
      'pierce',
      'radiation',
      'stool',
      'booth',
      'coherent',
      'souvenir',
      'plague n/v',
      'plague sb with sth',
      'intimate',
      'fuss',
      "Don't make a fuss",
      'wax',
      'concede v',
      'whale',
      'crust 2',
      'insight',
      'colony',
      'deliberate',
      'catalog',
      'liver',
      'inevitable',
      'whilst',
      'lid',
      'humble',
      'a modest and humble man',
      'grape',
      'ounce',
      'ashamed',
      'You should be ashamed of yourself.',
      'whip n/v',
      'thesis',
    ],
    Day16: [
      'negotiate',
      'germ',
      'beam 2',
      'smash',
      'affection',
      'refugee',
      'inhabitant',
      'collective',
      'a collective decision',
      'hut',
      'snap',
      'optical',
      'fate',
      'wicked',
      'beard',
      'postage',
      'widow',
      'era',
      'His death marked the end of an era.',
      'insult',
      'freight',
      'wit',
      'hostile',
      'commute to',
      'installment',
      'the second instalment of a loan',
      'spouse',
      'trolley',
      'a supermarket trolley',
      'warehouse',
      'intact',
      'Only the medieval tower had ==remained intact==.',
      'spontaneous',
      'toss',
      'tuition',
      'commence / start',
      'Work will commence on the new building immediately.',
    ],
    Day17: [
      'preliminrary',
      'withstand',
      'scrape',
      'blast',
      'workshop 2',
      'generous',
      'revise',
      'senate',
      'grip v/n',
      'inferior',
      'worship',
      'fleet',
      'outlet',
      'attorney',
      'regulate',
      'feasible',
      'parcel',
      'The parcel was delivered last week.',
      'leap',
      'premier adj/n',
      'sparkel n/v',
      'wrinkle n/v',
      'resign from',
      'intensive',
      'wreck v/n',
      'federal',
      'deaf',
      'overtake',
      'Never try to overtake on a bend.',
      'yawn',
      'spray',
      'She sprayed herself with perfume.',
      'funeral',
      'acute',
      'halt',
      'coarse',
      'rust n/v',
      'rusty',
      'bolt n2/v',
      'tram',
      'commodity',
      'Commodity prices fell sharply.',
      'intrude',
      'intrude into',
      'Employers should not intrude into the private lives of their employees.',
      'preach',
      'startle v',
    ],
    Review1: [
      'grant n/v',
      "Britain could grant Spain's request.",
      'The university gets a goverment grant.',
      'scandal',
      'fable',
      'the fable of the fox and the crow',
      'rug',
      'stoop',
      'ferry n/v',
      'ferry passenger across the Channel',
      'submerge',
      'exclaim',
      'she exclaimed in shock',
      'crude',
      'impulse / impulsive',
      '',
      'spite',
      'She broke it just out of spite',
      'purse',
      'raid',
      'a FBI raid',
      'distress 2',
      'Luke’s behaviour caused his parents great distress.',
      'acute financial distress',
      'genuine',
      'gut',
      'He has a gut felling that Tom was lying',
      'defect',
      'a genetic defect',
      'allowance',
      'recite',
      'She recite a poem.',
      'compromise',
      '',
      'prescribe',
      'hatch',
      'The eggs take three days to hatch',
      'ornament',
      'The building style is plain, with very little ornanment.',
      'excursion',
      'The excursion to the Grand Canyon',
      'condemn',
      'Politicians were quickly to condemn the boming',
      'eliminate',
      'There is no solution that will totally eliminate the possibility of theft.',
      'bait',
      'We use worms as bait.',
      'folk',
      '',
      'invest',
      'curse',
      'Gilbert was cursing under his breath.',
      'hazard to',
      'Polluted water sources are a hazard to wildlife.',
      'fibre',
      'deficit',
      'patent',
      'He applied for a patent for a new method of removing paint.',
      'pillar',
      'ridge',
      'along the ridge',
      'curb',
      'curb the spread of the viurs',
      'haunt',
      'orphan',
      '',
      'famine',
      'the great potato famine in Ireland',
      'plural',
      'decay / rot',
      'solemn',
      'Their faces suddenly grew solemn.',
      'exile',
      'antique',
      'banquet',
      'deprive',
      'A lot of these children have been deprived of a normal home life.',
      'attic',
      '',
      'hatred',
      'A look of pure hatred flashed across her face.',
      'reveal',
      'induce',
      'Nothing would induce me to vote for him again.',
      'in conjunction with',
      'cease/ stop',
      'retreat',
      'They were attacked and forced to retreat.',
      'estate',
      'belly',
      'apparatus',
      'Astronauts have special breathing apparatus.',
      'ample',
      '',
      'prospect',
      'There are good prospects for growth in the retail sector.',
      'prominent',
      'a prominent Russian scientist',
      'deputy',
      'timber',
      'dignity',
      'Old people need to retain their dignity and independence.',
      'cellar / basement',
      'accountable to',
      'The government should be accountable to all the people of the country.',
      'diagnose',
      'She was diagnosed with breast cancer.',
      'institution',
      '',
      'compass',
      'instinct / intuition',
      'Animals have a natural instinct for survival.',
      'prosperous',
      'a prosperous landowner',
      'farewell',
      'a farewell speach',
      'priest',
      'mat / rug',
      'decent',
      'Don’t you have a decent jacket?',
      'confine',
      'We confined our study to ten cases.',
      'elaborate adj/v',
      'a very elaborate network',
      'McDonald refused to elaborate on his reasons for resigning.',
      'corrupt',
      'diligent a diligent student',
    ],
    Review2: [
      'saddle',
      'lest',
      'council',
      'counsel',
      'lodge n/v',
      'tropical',
      'portrait',
      'a family portrait',
      'harsh',
      'trumpet',
      'trunk 2',
      'reservoir',
      'twist',
      'cherish',
      'sin',
      'She needs to confess her sin and asks for forgiveness.',
      'sow',
      'Sow the seeds in late march.',
      'impose',
      'nursery',
      'deposit n/v',
      'We put down a deposit on the house.',
      'earnest',
      'in earnest conversation',
      'oblige',
      'convict',
      'discard',
      'Discard any old cleaning materials.',
      'deceive',
      'profound',
      '',
      'virtue',
      'undergo',
      'dictate',
      'proceed',
      'rival',
      'his chief rival for the job',
      'corridor',
      'diplomatic',
      'conquer',
      'The Normans conquered England in 1066.',
      'inflation',
      'heir',
      'brochure',
      'deficit v',
      'deficient n',
      'I am deficient in vitamin C.',
      'democracy',
      'obstacle',
      'Fear of change is an obstacle to progress.',
      'nuisance',
      'neglect',
      'herd',
      'mineral',
      'lane',
      'heave',
      'Alan heaved his suitcase onto his bed.',
      'dropout',
      'contaminate',
      'contempt',
      '',
      'restore',
      'receipt',
      'specimen',
      'vacuum',
      'barn',
      'compel',
      'bribe',
      'stride',
      'soak',
      'for the sake of sth/sb',
      'vapour',
      'water vapour',
      'haste',
      'In his haste to leave, he forgot his briefcase.',
      'grace',
      'ditch n/v',
      'The government has ditched plans to privatise the prison.',
      'scout',
      'fountain',
      'conscientious',
      'acquaint sb with sth',
      '',
      'skim',
      'vigorous',
      'disorder',
      'slam',
      'sleeve',
      'hereby',
      'conform / comply',
      'rotten',
      'The smell of rotten eggs',
      'rigid',
      'rigid method of education',
      'veteran',
      'a veteran of the WW2',
      'the veteran leader',
      'vibrate',
      'fatigue',
      "Sam's face was grey with fatigue.",
      "Sam's face was grey with fatigue.",
      'vice',
      'chop',
      'infectious',
      'erect v/adj',
      'vinegar',
      'dizzy',
      '',
      'dump / rubbish dump',
      'flourish',
      'The economy is booming and small businesses are flourishing',
      'loaf',
      'stain',
      'marvellous',
      'boast',
      'prevail',
      'the prevailing political culture.',
      'outset',
      'from the outset',
      'vulnerable',
      '',
      'spade',
      'oval',
      'damp',
      'plunge',
      'Oil price have plunged to a new low.',
      'readily',
      'persevere',
      'He persevere with his task.',
      'trifle',
      'brag',
      'resemble',
      'scold',
      'spectacular',
      'The spectacular landscape.',
      'dissolve',
      'Stir until the suger dissolves.',
      'ribbon',
      'scarce',
      'frost',
      'compact',
      'ward',
      '',
      'weave',
      'handwoven scarves',
      'crane',
      'dialect',
      'weed',
      'diameter',
      'soar',
      'Her tempreture soared.',
      'riot',
      'urban riot',
      'weep',
      'welfare',
      'stool',
      'booth',
      'a voting booth',
      'plague n/v',
      'The plague caused 100,000 deaths',
      'He was plagued by eye troubles.',

      'intimate',
      'concede',
      'I conceded that I had made a number of errors.',
      'inevitable',
      'whip',
      '',
      'refugee',
      'refugee camps',
      'inhabitant',
      'wicked',
      'postage',
      'insult',
      'Nobody insults my family and gets away with it!',
      'hostile',
      'hostile attitude',
      'intact',
      'Only the medieval tower had remained intact.',
      'commence',
      '',
      'blast',
      'revise',
      'We have revised our estimates of population growth.',
      'grip',
      'inferior',
      'wine of inferior quality',
      'fleet',
      'attorney',
      'resign',
      'She resigned from the government last week.',
      'deaf',
      'overtake',
      'coarse',
      'commodity',
      'intrude / disturb',
      'Would I be intruding if I came with you?',
      'startle',
      'I was startle to see Amanda',
      'acute',
      'The housing shortage is acute',
    ],
  },
  TOEFL: {
    Day1: [
      'pastel',
      'cultivate',
      'substitute n/v',
      'renaissance',
      'sweat n/v',
      'husk n/v',
      'tide 2',
      'pluralism',
      'vagrant',
      'grievous',
      'saucy',
      'disproportionata',
      'withhold',
      'nosy',
      'stumble 2',
      'renown',
      'scroll n',
      'obliterate',
      'colonization / colonize',
      'affiliate',
      'rancor / rancorous',
      'subculture',
      'strain n/v',
      'mediate',
      'exposition',
      'solicit 2',
      'leisure',
      'unravel',
      'nail 2',
      'unsubstantiated / substantiate',
      'stylized',
      'intrepid',
      'nominee',
      'panic',
      'lure n/v',
      'revere v',
      'aria',
      'facilitate',
      'reef',
      'feeble',
      'influx',
      'receptacle',
      'engulf',
      'unprecedented',
      'seep',
      'patriarch',
    ],
  },
};
